### ISSUE TITLE
Remove unnecessary gem dependencies

### ISSUE THREAD

**Issue by barzilay** [spriteCloud/lapis-lazuli#54]
Currently lapis lazuli has alot of gem dependencies, see Gemfile.lock:
```
lapis_lazuli (1.0.1)
      byebug (~> 9)
      cucumber (~> 2)
      facets (~> 3.1)
      faraday (~> 0.9)
      faraday_json (~> 0.1)
      faraday_middleware (~> 0.10)
      ffi (~> 1.9)
      json (~> 2.0)
      minitest (~> 5.10)
      multi_xml (~> 0.6)
      rspec (~> 3.5)
      selenium-webdriver (~> 3)
      teelogger (~> 0.5)
      thor (~> 0.19)
      watir (~> 6)
```

Im sure some of them arent needed and can be removed. We'll need to investigate which ones can safely be removed. My guess is that we end up with something like:

```
lapis_lazuli (1.0.1)
     cucumber (~> 2)
      selenium-webdriver (~> 3)
      teelogger (~> 0.5)
      watir (~> 6)
```

**Comment by sjieg** [comment]
Fix is now on the development branch & testing on calliope.

```
    lapis_lazuli (1.0.3dev)
      cucumber (~> 2)
      faraday_json (~> 0.1)
      faraday_middleware (~> 0.10)
      minitest (~> 5.10)
      multi_xml (~> 0.6)
      selenium-webdriver (~> 3.2.2)
      teelogger (~> 0.5)
      watir (~> 6.1.0)
```

**Comment by barzilay** [comment]
Oops:

Heb vandaag toevallig mijn ruby geupgrade naar de nieuwe versie, aangezien ik nog op 2.3.0 zat (nu 2.3.3). 

De mooie en verbeterde handleiding opgevolgd en kreeg een probleem bij het volgende:

C:\Ruby23\projects>lapis_lazuli create blokker
C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- thor (LoadError)
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/lapis_lazuli-1.0.3/lib/lapis_lazuli/cli.rb:8:in `<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/lapis_lazuli-1.0.3/bin/lapis_lazuli:2:in `<top (required)>'
        from C:/Ruby23/bin/lapis_lazuli:22:in `load'
        from C:/Ruby23/bin/lapis_lazuli:22:in `<main>'

**Comment by emkaem** [comment]
Needed to install another gem before I could use "lapis_lazuli create <project_name>"
After installing Facets creating a new project worked:

```
C:\Ruby23\projects>lapis_lazuli create TestProject233
      create  TestProject233
      create  TestProject233/config
      create  TestProject233/features
      create  TestProject233/features/step_definitions
      create  TestProject233/features/support
      create  TestProject233/logs
      create  TestProject233/results
      create  TestProject233/screenshots
         run  git config --get user.name from "."
         run  git config --get user.email from "."
C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- facets/string/lchomp (LoadError)
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/lapis_lazuli-1.0.3/lib/lapis_lazuli/generators/cucumber.rb:73:in `copy_template'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:40:in `block in register'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/lapis_lazuli-1.0.3/bin/lapis_lazuli:3:in `<top (required)>'
        from C:/Ruby23/bin/lapis_lazuli:22:in `load'
        from C:/Ruby23/bin/lapis_lazuli:22:in `<main>'
```
