### ISSUE TITLE
Selenium-grid error 500 when using selenuim-webdriver > 3.5.1

### ISSUE THREAD

**Issue by mark0203** [spriteCloud/lapis-lazuli#79]
HAPPY FLOW: When I use selenium-webdriver version 3.4.0 I can use the grid just fine 

```ruby
irb(main):001:0> gem 'selenium-webdriver', '=3.4.0'
=> true
irb(main):002:0> require 'lapis_lazuli'
=> true
irb(main):003:0> include LapisLazuli
=> Object
irb(main):004:0> url2 = "http://localhost:4444/wd/hub"
=> "http://localhost:4444/wd/hub"
irb(main):005:0> browser :remote, {
irb(main):006:1*   :url => url2,
irb(main):007:1*   :caps => {
irb(main):008:2*     "browserName" => "chrome",
irb(main):009:2* "platformName" => "Android",
irb(main):010:2* "deviceName" => "Nexus5",
irb(main):011:2* }
irb(main):012:1> }
Unable to find a configuration file, defaulting to empty config.yml.
No default device, nor a selected device was set. Browser default settings will be loaded. More info: http://testautomation.info/Lapis_Lazuli:Device_Simulation
=> #<LapisLazuli::Browser:0x305d540 @browser_wanted=:remote, @optional_data={:url=>"http://localhost:4444/wd/hub", :caps=>{"browserName"=>"chrome", "platformName"=>"Android", "deviceName"=>"Nexus5"}}, @browser_name="remote", @browser=#<Watir::Browser:0x..f8a94e8f4 url="data:," title="">>
```

MISSING INFO FLOW: But when I use selenium-webdriver version 3.5.1 I get an error 500 and can't start up the grid browser

```ruby
irb(main):001:0> gem 'selenium-webdriver', '=3.5.1'
=> true
irb(main):002:0> require 'lapis_lazuli'
=> true
irb(main):003:0> include LapisLazuli
=> Object
irb(main):004:0> url2 = "http://localhost:4444/wd/hub"
=> "http://localhost:4444/wd/hub"
irb(main):005:0> browser :remote, {
irb(main):006:1*   :url => url2,
irb(main):007:1*   :caps => {
irb(main):008:2*     "browserName" => "chrome",
irb(main):009:2* "platformName" => "Android",
irb(main):010:2* "deviceName" => "Nexus5",
irb(main):011:2* }
irb(main):012:1> }
Unable to find a configuration file, defaulting to empty config.yml.
No default device, nor a selected device was set. Browser default settings will be loaded. More info: http://testautomation.info/Lapis_Lazuli:Device_Simulation
You can now pass values directly into Watir::Browser opt without needing to use :desired_capabilities
Selenium::WebDriver::Error::ServerError: status code 500
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/bridge.rb:103:in `create_session'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/bridge.rb:54:in `handshake'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/driver.rb:39:in `initialize'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/common/driver.rb:58:in `new'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/common/driver.rb:58:in `for'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver.rb:86:in `for'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.7.0/lib/watir/browser.rb:48:in `initialize'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/lapis_lazuli-2.0.0/lib/lapis_lazuli/browser.rb:411:in `new'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/lapis_lazuli-2.0.0/lib/lapis_lazuli/browser.rb:411:in `create_driver'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/lapis_lazuli-2.0.0/lib/lapis_lazuli/browser.rb:277:in `init'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/lapis_lazuli-2.0.0/lib/lapis_lazuli/browser.rb:123:in `start'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/lapis_lazuli-2.0.0/lib/lapis_lazuli/browser.rb:84:in `initialize'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/lapis_lazuli-2.0.0/lib/lapis_lazuli/world/browser.rb:56:in `new'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/lapis_lazuli-2.0.0/lib/lapis_lazuli/world/browser.rb:56:in `block in browser'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/lapis_lazuli-2.0.0/lib/lapis_lazuli/runtime.rb:50:in `set_if'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/lapis_lazuli-2.0.0/lib/lapis_lazuli/world/browser.rb:51:in `browser'
        from (irb):5
        from C:/Ruby23/bin/irb.cmd:19:in `<main>'
```

I'm not sure if I'm just missing the info (how to pass on the capabilities correctly), or if this is a bug.

**Comment by sjieg** [comment]
Not sure, but how is this an issue for LL, if the error occurs when you change the Selenium version?

You might also want to look into the Watir versions, I've reported a bug just today about starting a browser with a custom `:profile`
https://github.com/watir/watir/issues/625
