### ISSUE TITLE
IRB: RuntimeError: Error loading file: config/config.yml

### ISSUE THREAD

**Issue by sjieg** [spriteCloud/lapis-lazuli#98]
I should have fixed this issue in LL2.1.2, but a colleague showed me this issue.

I haven't been able to reproduce it yet, so I'll have to look into the code how we're handling this.
```
irb(main):003:0> browser.goto "test.salesforce.com"

RuntimeError: Error loading file: config/config.yml (config/config.yml): mapping values are not allowed in this context at line 60 column 11

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/world/config.rb:193:in `rescue in get_config_from_file'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/world/config.rb:182:in `get_config_from_file'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/world/config.rb:175:in `add_config_from_file'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/world/config.rb:140:in `block (2 levels) in load_config'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/world/config.rb:135:in `each'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/world/config.rb:135:in `block in load_config'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/world/config.rb:109:in `each'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/world/config.rb:109:in `load_config'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/world/config.rb:66:in `init'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/world/config.rb:332:in `env_or_config'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/browser.rb:253:in `init'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/browser.rb:123:in `start'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/browser.rb:84:in `initialize'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/world/browser.rb:56:in `new'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/world/browser.rb:56:in `block in browser'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/runtime.rb:50:in `set_if'

        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/lapis_lazuli-2.1.3/lib/lapis_lazuli/world/browser.rb:51:in `browser'

        from (irb):3

        from C:/Ruby24-x64/bin/irb.cmd:19:in `<main>'

irb(main):004:0> LapisLazuli::WorldModule::Config.add_config("config/config.yml")

=> ["config/config.yml"]

irb(main):005:0> browser.goto "test.salesforce.com"

```

**Comment by sjieg** [comment]
This is a syntax error for a YML file. Cannot reproduce locally.
